parameters:
#    sapiens_blog.example.class: Sapiens\BlogBundle\Example

services:
#    sapiens_blog.example:
#        class: %sapiens_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
